NUXY-SVC:
  api-selectUser-001:
    url: /selectUser/{userId}
  api-selectUserList-001:
    url: /selectUser
  api-selectUserList-002:
    url: /v2/selectUser
  api-selectUserLiteral-001:
    url: /selectUserLiteral/{userId}
  api-selectUserFqn-001:
    url: /selectUserFqn/{userId}
  api-selectUserWildcard-001:
    url: /selectUserWildcard/{userId}
  api-selectUserLocal-001:
    url: /selectUserLocal/{userId}
  api-selectUserLocalPublic-001:
    url: /selectUserLocalPublic/{userId}
  api-selectUserIface-001:
    url: /selectUserIface/{userId}
  api-selectUserParent-001:
    url: /selectUserParent/{userId}
  api-selectUserChain-001:
    url: /selectUserChain/{userId}
  api-selectUserChain-002:
    url: /v2/selectUserChain/{userId}
  api-selectUserNotFinal-001:
    url: /selectUserNotFinal/{userId}
  api-selectPoint-001:
    url: /selectPoint/{custId}
  api-selectCust-001:
    url: /selectCust/{custId}
  api-selectCustList-001:
    url: /selectCust
  saveCust-001:
    url: /saveCust
  api-createInvoice-001:
    url: /createInvoice/{invoiceId}
  api-requestPayment-001:
    url: /requestPayment/{paymentId}
NUXZ-SVC:
  selectCust-001:
    url: /selectCust/{custId}
  selectCustList-001:
    url: /selectCust
  api-selectPoint-001:
    url: /selectPoint/{custId}
