service:
  apim:
    url: https://openapi.lg...
  apim-pv:
    url: https://openapi.lg...
  apim-pb:
    url: https://openapi.lg...
amdocs:
  url: https://openapi.lg...
NUXY-SVC:
  url: https://domain01.com
NUXZ-SVC:
  url: https://domain02.com
NUXA-SVC:
  url: https://domain03.com
